# Generated by Django 3.2.9 on 2021-12-03 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank='False', max_length=200, null='False')),
                ('image', models.ImageField(blank='False', null='False', upload_to='')),
                ('description', models.TextField(blank='False', null='False')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank='False', max_length=500, null='False')),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank='False', max_length=200, null='False')),
                ('image', models.ImageField(blank='False', null='False', upload_to='')),
                ('sentence', models.TextField(blank='False', null='False')),
                ('color', models.CharField(blank='False', max_length=64, null='False')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kidedu.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
